ci: SA-31 - env variable create

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -11,8 +11,24 @@ env:
 
 
 jobs:
-  build_backend:
+  create-envfile:
     runs-on: ubuntu-latest
+
+    steps:
+      - name: Make envfile
+        uses: SpicyPizza/create-envfile@v1.3
+        with:
+          envkey_DEBUG: false
+          envkey_SOME_API_KEY: "123456abcdef"
+          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
+          some_other_variable: foobar
+          directory: <directory_name>
+          file_name: .env
+          fail_on_empty: true
+
+  build-backend:
+    runs-on: ubuntu-latest
+    needs: [ create-envfile ]
 
     steps:
       - name: Check out the repo
@@ -21,8 +37,9 @@ jobs:
       - name: Build backend image
         run: docker build ./backend --file backend/Dockerfile
 
-  build_nginx:
+  build-nginx:
     runs-on: ubuntu-latest
+    needs: [ create-envfile ]
 
     steps:
       - name: Check out the repo
@@ -33,7 +50,7 @@ jobs:
 
   lint:
     runs-on: ubuntu-latest
-    needs: [ build_backend ]
+    needs: [ build-backend ]
     steps:
       - name: Check out the repo
         uses: actions/checkout@v3
@@ -43,21 +60,21 @@ jobs:
         with:
           extra_args: flake8 --all-files
 
-#        TODO: env files
-#      - name: Check migrations
-#        run: docker-compose run --rm backend poetry run python manage.py makemigrations --dry-run --check || (echo 'Error in migrations dry-check' && exit 1)
+  #        TODO: env files
+  #      - name: Check migrations
+  #        run: docker-compose run --rm backend poetry run python manage.py makemigrations --dry-run --check || (echo 'Error in migrations dry-check' && exit 1)
 
   test:
     runs-on: ubuntu-latest
-    needs: [ build_backend ]
+    needs: [ build-backend ]
 
     steps:
       - name: Run tests
         run: echo "Running tests on $IMAGE"
 
-  push_backend_to_container_repository:
+  push-backend-to-container-repository:
     name: Push backend Docker image to container repository
-    needs: [ test, lint, build_nginx ]
+    needs: [ test, lint, build-nginx ]
     runs-on: ubuntu-latest
 
     steps:
@@ -67,9 +84,9 @@ jobs:
       - name: Push image to GitHub Container Registry
         run: echo "Push $IMAGE image to GitHub Container Registry"
 
-  push_nginx_to_container_repository:
+  push-nginx-to-container-repository:
     name: Push backend Docker image to container repository
-    needs: [ test, lint, build_nginx ]
+    needs: [ test, lint, build-nginx ]
     runs-on: ubuntu-latest
 
     steps:
@@ -81,7 +98,7 @@ jobs:
 
   deploy:
     name: Deploy
-    needs: [ push_backend_to_container_repository, push_nginx_to_container_repository ]
+    needs: [ push-backend-to-container-repository, push-nginx-to-container-repository ]
     runs-on: ubuntu-latest
 
     steps:
