ci: SA-31 - test

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -37,12 +37,12 @@ jobs:
     steps:
       - name: Lint
         run: |
-          run poetry run pre-commit run --all-files --show-diff-on-failure && \
-          run poetry run python manage.py makemigrations --dry-run --check || (echo 'Error in migrations dry-check' && exit 1)
+          poetry run pre-commit run --all-files --show-diff-on-failure && \
+          poetry run python manage.py makemigrations --dry-run --check || (echo 'Error in migrations dry-check' && exit 1)
 
   test:
     runs-on: ubuntu-latest
-    needs: [ build_backend ]
+    needs: [ lint ]
 
     steps:
       - name: Run tests
@@ -50,7 +50,7 @@ jobs:
 
   push_backend_to_container_repository:
     name: Push backend Docker image to container repository
-    needs: [ build_backend, build_nginx ]
+    needs: [ test, lint, build_nginx ]
     runs-on: ubuntu-latest
 
     steps:
@@ -62,7 +62,7 @@ jobs:
 
   push_nginx_to_container_repository:
     name: Push backend Docker image to container repository
-    needs: [ build_backend, build_nginx ]
+    needs: [ test, lint, build_nginx ]
     runs-on: ubuntu-latest
 
     steps:
@@ -71,3 +71,12 @@ jobs:
 
       - name: Push image to GitHub Container Registry
         run: echo "Push $IMAGE image to GitHub Container Registry"
+
+  deploy:
+    name: Deploy
+    needs: [ push_backend_to_container_repository, push_nginx_to_container_repository ]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Push to $ENVIRONMENT environment
+        run: echo "Push mock"
