ci: SA-31 - env variable create

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -23,6 +23,9 @@ jobs:
           file_name: .env
           fail_on_empty: true
 
+      - name: Check env file in another job
+        run: cat .env
+
   build-backend:
     runs-on: ubuntu-latest
     needs: [ create-envfile ]
@@ -33,6 +36,9 @@ jobs:
 
       - name: Build backend image
         run: docker build ./backend --file backend/Dockerfile
+
+      - name: Check env file in another job
+        run: cat .env
 
   build-nginx:
     runs-on: ubuntu-latest
@@ -57,9 +63,8 @@ jobs:
         with:
           extra_args: flake8 --all-files
 
-  #        TODO: env files
-  #      - name: Check migrations
-  #        run: docker-compose run --rm backend poetry run python manage.py makemigrations --dry-run --check || (echo 'Error in migrations dry-check' && exit 1)
+      - name: Check migrations
+        run: docker-compose run --rm backend poetry run python manage.py makemigrations --dry-run --check || (echo 'Error in migrations dry-check' && exit 1)
 
   test:
     runs-on: ubuntu-latest
