ci: SA-31 - test

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -3,62 +3,71 @@ name: Build & Test
 on:
   push:
   pull_request:
+
 env:
-  IMAGE_NAME: sportagenda_backend
+  ENVIRONMENT: develop
+  BACKEND_IMAGE_NAME: backend
+  NGINX_IMAGE_NAME: nginx
+
 
 jobs:
-  build:
+  build_backend:
     runs-on: ubuntu-latest
 
     steps:
       - name: Check out the repo
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
       - name: Build backend image
         run: docker build ./backend --file backend/Dockerfile
 
-  test:
+  build_nginx:
     runs-on: ubuntu-latest
-    needs: [ build ]
 
     steps:
       - name: Check out the repo
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
+      - name: Build backend image
+        run: docker build ./backend --file backend/Dockerfile
+
+  lint:
+    runs-on: ubuntu-latest
+    needs: [ build_backend ]
+    steps:
+      - name: Lint
+        run: |
+          run poetry run pre-commit run --all-files --show-diff-on-failure && \
+          run poetry run python manage.py makemigrations --dry-run --check || (echo 'Error in migrations dry-check' && exit 1)
+
+  test:
+    runs-on: ubuntu-latest
+    needs: [ build_backend ]
+
+    steps:
       - name: Run tests
-        run: echo "Running tests"
+        run: echo "Running tests on $IMAGE"
 
-  push_to_container_repository:
+  push_backend_to_container_repository:
     name: Push backend Docker image to container repository
-    needs: [ build, test ]
+    needs: [ build_backend ]
     runs-on: ubuntu-latest
 
     steps:
       - name: Log into GitHub Container Registry
-        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
 
       - name: Push image to GitHub Container Registry
-        run: |
-          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
+        run: echo "Push $IMAGE image to GitHub Container Registry"
 
-          # Change all uppercase to lowercase
-          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
+  push_backend_to_container_repository:
+    name: Push backend Docker image to container repository
+    needs: [ build_backend ]
+    runs-on: ubuntu-latest
 
-          # Strip git ref prefix from version
-          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
-          echo VERSION=$VERSION
+    steps:
+      - name: Log into GitHub Container Registry
+        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
 
-          # Strip "v" prefix from tag name
-          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
-          echo VERSION=$VERSION
-
-          # Use Docker `latest` tag convention
-          [ "$VERSION" == "master" ] && VERSION=latest
-
-          echo IMAGE_NAME=$IMAGE_NAME
-          echo IMAGE_ID=$IMAGE_ID
-          echo VERSION=$VERSION
-          echo docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
-
-          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
-          docker push $IMAGE_ID:$VERSION
+      - name: Push image to GitHub Container Registry
+        run: echo "Push $IMAGE image to GitHub Container Registry"
